- name: Add an agent user group
  ansible.builtin.group:
    name: "{{ az_devops_agent_group }}"
    state: present
    become: true

- name: Add an agent user
  ansible.builtin.user:
    name: "{{ az_devops_agent_user }}"
    group: "{{ az_devops_agent_group }}"
    uid: "{{ az_devops_agent_uid|default(omit) }}"
    comment: "Azure DevOps Agent"
    shell: /bin/bash
  become: true

- name: Create directories
  ansible.bulitin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ az_devops_agent_user }}"
    group: "{{ az_devops_agent_group }}"
    mode: 0755
  loop:
    - "{{ az_devops_agent_folder }}"
    - "{{ az_devops_work_folder }}"
  become: true

- name: Install Legacy dependencies
  ansible.builtin.apt:
    name: "{{ az_devops_agent_legacy_dependencies }}"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Patch openssl config when using legacy ssl 1 on modern system
  ansible.builtin.lineinfile:
    dest: /etc/ssl/openssl.cnf
    regexp: '^openssl_conf ='
    line: '# openssl_conf ='
  when: az_devops_agent_legacy_dependencies | length>0

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ az_devops_agent_dependencies }}"
    state: present
  become: true

- name: Check if svc.sh exists
  ansible.builtin.stat:
    path: "{{ '/'.join((az_devops_agent_folder, 'svc.sh')) }}"
  register: svc_sh
  become: true
  changed_when: false
  check_mode: no

- name: Check service status
  ansible.builtin.command: ./svc.sh status
  become: true
  args:
    chdir: "{{ az_devops_agent_folder }}"
  register: svc_status
  changed_when: false
  check_mode: no
  when: svc_sh.stat.exists

- name: Check if bin/Agent.Listener exists
  ansible.builtin.stat:
    path: "{{ '/'.join((az_devops_agent_folder, 'bin/Agent.Listener')) }}"
  register: bin_agent_listener
  become: true
  changed_when: false
  check_mode: no

- name: Check agent version
  ansible.builtin.command: ./bin/Agent.Listener --version
  become: true
  args:
    chdir: "{{ az_devops_agent_folder }}"
  register: agent_listener_version
  changed_when: false
  check_mode: no
  when: bin_agent_listener.stat.exists

- name: Set agent config facts
  ansible.builtin.set_fact:
    agent_cmd_args:
      - "./config.sh"
      - "--unattended"
      - "--acceptteeeula"
      - "--url '{{ az_devops_server_url }}'"
      - "--work '{{ az_devops_work_folder }}'"
      - "--auth PAT"
      - "--token '{{ az_devops_accesstoken }}'"
      - "--runasservice"
    build_agent_cmd_args:
      - "--pool '{{ az_devops_agent_pool_name }}'"
      - "--agent '{{ az_devops_agent_name }}'"
    deployment_agent_cmd_args:
      - "--deploymentgroup"
      - "--deploymentgroupname '{{ az_devops_deployment_group_name }}'"
      - "--projectname '{{ az_devops_project_name }}'"
    resource_agent_cmd_args:
      - "--environment"
      - "--environmentname '{{ az_devops_environment_name }}'"
      - "--agent '{{ az_devops_agent_name }}'"
      - "--projectname '{{ az_devops_project_name }}'"
    service_is_installed: "{{ svc_status.stdout is defined and svc_status.stdout is not regex('not installed') }}"
    service_is_running: "{{ svc_status.stdout is defined and svc_status.stdout is regex('active \\(running\\)') }}"
    is_requested_version: "{{ bin_agent_listener.stat.exists and agent_listener_version.stdout is defined and agent_listener_version.stdout == az_devops_agent_version }}"

- name: Determine if the agent should be reconfigured or replaced
  ansible.builtin.set_fact:
    reconfigure_or_replace: "{{ az_devops_reconfigure_agent or az_devops_agent_replace_existing or not is_requested_version }}"

- name: Add deployment group tags
  ansible.builtin.set_fact:
    deployment_agent_cmd_args: "{{ deployment_agent_cmd_args }} +
      ['--addDeploymentGroupTags', '--deploymentGroupTags \\'{{ az_devops_deployment_group_tags }}\\'']"
  when:
    - az_devops_deployment_group_tags is defined

- name: Set proxy
  ansible.builtin.set_fact:
    agent_cmd_args: "{{ agent_cmd_args }} + ['--proxyurl \\'{{ az_devops_proxy_url }}\\'', '--proxyusername \\'{{ az_devops_proxy_username }}\\'', '--proxypassword \\'{{ az_devops_proxy_password }}\\'']"
  when:
    - az_devops_proxy_url is defined

- name: Download and unarchive
  ansible.builtin.unarchive:
    src: "{{ az_devops_agent_package_url }}"
    dest: "{{ az_devops_agent_folder }}"
    remote_src: yes
    owner: "{{ az_devops_agent_user }}"
    group: "{{ az_devops_agent_group }}"
  become: true
  when:
    - (not service_is_installed) or reconfigure_or_replace

- name: Uninstall agent service
  ansible.builtin.command: ./svc.sh uninstall
  become: true
  args:
    chdir: "{{ az_devops_agent_folder }}"
    removes: "{{ az_devops_agent_folder }}/runsvc.sh"
  when:
    - service_is_installed
    - reconfigure_or_replace

- name: Unconfigure agent
  ansible.builtin.command: "./config.sh remove --auth PAT --token {{ az_devops_accesstoken }}"
  args:
    chdir: "{{ az_devops_agent_folder }}"
    removes: "{{ az_devops_agent_folder }}/.agent"
  become: true
  become_user: "{{ az_devops_agent_user }}"
  when:
    - service_is_installed
    - reconfigure_or_replace

- name: Add '--replace' configuration argument
  ansible.builtin.set_fact:
    build_agent_cmd_args: "{{ build_agent_cmd_args }} + ['--replace']"
    deployment_agent_cmd_args: "{{ build_agent_cmd_args }} + ['--replace']"
    resource_agent_cmd_args: "{{ resource_agent_cmd_args }} + ['--replace']"
  when:
    - az_devops_agent_replace_existing

- name: Configure agent as a build server
  ansible.builtin.command: "{{ (agent_cmd_args + build_agent_cmd_args) | join(' ') }}"
  args:
    chdir: "{{ az_devops_agent_folder }}"
    creates: "{{ az_devops_agent_folder }}/.agent"
  become: true
  become_user: "{{ az_devops_agent_user }}"
  when:
    - az_devops_agent_role == 'build'
    - (not service_is_installed) or reconfigure_or_replace

- name: Configure agent as a deployment server
  ansible.builtin.command: "{{ (agent_cmd_args + deployment_agent_cmd_args) | join(' ') }}"
  args:
    chdir: "{{ az_devops_agent_folder }}"
    creates: "{{ az_devops_agent_folder }}/.agent"
  become: true
  become_user: "{{ az_devops_agent_user }}"
  when:
    - az_devops_agent_role == 'deployment'
    - (not service_is_installed) or reconfigure_or_replace

- name: Configure agent as an environment resource
  ansible.builtin.command: "{{ (agent_cmd_args + resource_agent_cmd_args) | join(' ') }}"
  args:
    chdir: "{{ az_devops_agent_folder }}"
    creates: "{{ az_devops_agent_folder }}/.agent"
  become: true
  become_user: "{{ az_devops_agent_user }}"
  when:
    - az_devops_agent_role == 'resource'
    - (not service_is_installed) or reconfigure_or_replace

- name: Set provided user defined capabilities
  community.general.ini_file:
    path: "{{ az_devops_agent_folder }}/.env"
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
    owner: "{{ az_devops_agent_user }}"
    group: "{{ az_devops_agent_group }}"
  loop: "{{ az_devops_agent_user_capabilities | default({}) | dict2items }}"
  become: true

- name: Install agent service
  ansible.builtin.command: ./svc.sh install {{ az_devops_agent_user }}
  become: true
  args:
    chdir: "{{ az_devops_agent_folder }}"
  when:
    - (not service_is_installed) or reconfigure_or_replace

- name: Start agent service
  ansible.builtin.command: ./svc.sh start
  become: true
  args:
    chdir: "{{ az_devops_agent_folder }}"
  when:
    - (not service_is_running) or reconfigure_or_replace
