- name: Add an agent user
  win_user:
    name: "{{ az_devops_agent_user }}"
    password: "{{ az_devops_agent_password }}"
    state: present
    password_never_expires: true
  become: yes

- name: Ensure chocolatey is present
  win_chocolatey:
    name: chocolatey
    state: present

# The full list of parameters is documented here:
# https://github.com/flcdrg/au-packages/blob/master/azure-pipelines-agent/README.md

- name: Set basic agent package parameters
  set_fact:
    common_install_options:
      - "/Directory:{{ az_devops_agent_folder }}"
      - "/Url:{{ az_devops_server_url }}"
      - "/Token:{{ az_devops_accesstoken }}"
      - "/Auth:PAT"
      - "/Pool:{{ az_devops_agent_pool_name }}"
      - "/Work:_work"
      - "/LogonAccount:{{ az_devops_agent_user }}"
      - "/LogonPassword:{{ az_devops_agent_password }}"
    build_agent_install_options:
      - "/Pool:{{ az_devops_agent_pool_name }}"
      - "/AgentName:{{ az_devops_agent_name }}"
    deployment_install_options:
      - "/DeploymentGroup"
      - "/DeploymentGroupName:{{ az_devops_deployment_group_name }}"
      - "/ProjectName:{{ az_devops_project_name }}"
    resource_agent_install_options:
      - "/Environment"
      - "/EnvironmentName:{{ az_devops_environment_name }}"
      - "/AgentName:{{ az_devops_agent_name }}"
      - "/ProjectName:{{ az_devops_project_name }}"

- name: Add '/Replace' configuration argument
  set_fact:
    common_install_options: "{{ common_install_options }} + ['/Replace']"
  when:
    - az_devops_agent_replace_existing

- name: Add deployment group tags
  set_fact:
    deployment_install_options: "{{ deployment_install_options }} + ['/DeploymentGroupTags:{{ az_devops_deployment_group_tags }}']"
  when:
    - az_devops_deployment_group_tags is defined

- name: Add az_devops_proxy_url
  set_fact:
    common_install_options: "{{ common_install_options }} + ['/ProxyUrl:{{ az_devops_proxy_url }}']"
  when:
    - az_devops_proxy_url is defined and az_devops_proxy_url

- name: Add az_devops_proxy_username
  set_fact:
    common_install_options: "{{ common_install_options }} + ['/ProxyUserName:{{ az_devops_proxy_username }}']"
  when:
    - az_devops_proxy_username is defined and az_devops_proxy_username

- name: Add az_devops_proxy_password
  set_fact:
    common_install_options: "{{ common_install_options }} + ['/ProxyPassword:{{ az_devops_proxy_password }}']"
  when:
    - az_devops_proxy_password is defined and az_devops_proxy_password

- name: Configure agent as a build server
  set_fact:
    az_devops_agent_package_params: "{{ common_install_options }} + {{ build_agent_install_options }}"
  when:
     - az_devops_agent_role == 'build'

- name: Configure agent as a deployment server
  set_fact:
    az_devops_agent_package_params: "{{ common_install_options }} + {{ deployment_install_options }}"
  when:
     - az_devops_agent_role == 'deployment'

- name: Configure agent as an environment resource
  set_fact:
    az_devops_agent_package_params: "{{ common_install_options }} + {{ resource_agent_install_options }}"
  when:
     - az_devops_agent_role == 'resource'

- name: Install azure-pipelines-agent package
  win_chocolatey:
    name: azure-pipelines-agent
    state: present
    version: "{{ az_devops_agent_version }}"
    package_params: "{{ az_devops_agent_package_params | join(' ') }}"
